### ISSUE TITLE
Ejecución con node

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-12#1]
Si bien no es un error, se espera que nodemon sea usado en un entorno de desarrollo únicamente (lo que se suele depositar en el script dev, corriendo el proyecto con `npm run dev`), por lo que el lugar de un script llamado start muy probablemente lo querríamos ocupar para la ejecución simple con node, esto se notaría si en el futuro quieren subir su proyecto. 
https://github.com/0623CIFSNCN05LAED/grupo-12/blob/da9c31067b974a7b5ed92d8255878cd9168f0cdd/package.json#L9-L11

**Comment by reak97** [comment]
corregido
