### ISSUE TITLE
Tener cuidado con la implementación de scripts

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-12#2]
Si bien cumple con la función que quieren implementar. Se sugiere tener cuidado y responsabilidad al incorporar contenido que excede al contenido ya visto en clase (esencialmente porque la idea es que se vayan implementando los contenidos vistos y, mucho mas importante, todos los integrantes deben poder entender todo lo que se encuentra en el proyecto)

El contenido en cuestión se encontraría en el logo de todos los sitios
https://github.com/0623CIFSNCN05LAED/grupo-12/blob/da9c31067b974a7b5ed92d8255878cd9168f0cdd/src/views/home.html#L28
https://github.com/0623CIFSNCN05LAED/grupo-12/blob/da9c31067b974a7b5ed92d8255878cd9168f0cdd/src/views/login.html#L28
https://github.com/0623CIFSNCN05LAED/grupo-12/blob/da9c31067b974a7b5ed92d8255878cd9168f0cdd/src/views/register.html#L28
https://github.com/0623CIFSNCN05LAED/grupo-12/blob/da9c31067b974a7b5ed92d8255878cd9168f0cdd/src/views/product-detail.html#L28
https://github.com/0623CIFSNCN05LAED/grupo-12/blob/da9c31067b974a7b5ed92d8255878cd9168f0cdd/src/views/product-cart.html#L28

**Comment by reak97** [comment]
corregido
