### ISSUE TITLE
Segregación de responsabilidades

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-12#22]
No le corresponde a las rutas manejar ni los archivos de imágenes, debería ir en su módulos correspondiente, multer es un middleware

https://github.com/0623CIFSNCN05LAED/grupo-12/blob/a709d78969332c789e53b6b904095c2e40eb3710/src/routes/products-router.js#L6-L19

**Comment by meruiz0203** [comment]
Resuelto en la carpeta de Middleware
