### ISSUE TITLE
Orden de hojas de estilo y Font-Awesome

### ISSUE THREAD

**Issue by LuluAylen00** [0623CIFSNCN05LAED/grupo-12#3]
Algo presente también en todas las páginas.
Como anotación: es importante que su hoja de estilos se encuentre por debajo de todas las demás hojas de estilo que pudiesen incorporarse, ya que Font Awesome vinculado de esa manera pone sus etiquetas style por debajo. Además, como sugerencia, la vinculación podría realizarse de una manera mas sencilla obteniendo la hoja de estilos directamente con el recurso que pueden encontrar en CDNJS.

https://github.com/0623CIFSNCN05LAED/grupo-12/blob/da9c31067b974a7b5ed92d8255878cd9168f0cdd/src/views/home.html#L16-L18

**Comment by reak97** [comment]
corregido
