### ISSUE TITLE
duplicación

### ISSUE THREAD

**Issue by LuiosDyet** [0623CIFSNCN05LAED/grupo-12#32]
qué diferencia hay entre este archivo y su partial?

https://github.com/0623CIFSNCN05LAED/grupo-12/blob/a709d78969332c789e53b6b904095c2e40eb3710/src/views/product-list-bikes.ejs#L14

**Comment by meruiz0203** [comment]
El archivo del partial forma parte del la vista(info principal), donde se listan las bicicletas con su encabezado y su pié de pagina.
